/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/island/island2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Island_2 = ({ scale, position, onClick, props }) => {
  const { nodes, materials } = useGLTF('./models/island/island_2.glb')
  const meshRef = useRef();
  
  const handleOnClick = () => {
    onClick(); // 부모 컴포넌트로 클릭 이벤트 전달
  };

  return (
    <mesh
      ref={meshRef}
      scale={scale}
      position={position}
      onClick={handleOnClick}
    >
    <group {...props} dispose={null} rotation-y={1.2} color={"black"}>
      <group position={[1.397, 50.417, -38.659]} rotation={[-Math.PI / 2, 0, -0.9]} scale={[0.157, 0.157, 2.074]}>
        <mesh geometry={nodes['Tree2_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
        <mesh geometry={nodes['Tree2_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
      </group>
      <group position={[39.338, 47.879, -4.395]} rotation={[-Math.PI / 2, 0, -Math.PI / 9]} scale={[0.153, 0.153, 2.397]}>
        <group position={[27.99, 0, 0]}>
          <mesh geometry={nodes['Tree3_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
          <mesh geometry={nodes['Tree3_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
        </group>
      </group>
      <group position={[-71.794, 34.472, 16.339]} rotation={[0, -1.571, 0]} scale={[1, 1, 1.286]}>
        <mesh geometry={nodes['Dock_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
        <mesh geometry={nodes['Dock_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
      </group>
      <group position={[-1.454, 42.918, 27.832]} rotation={[-Math.PI / 2, 0, -1.134]} scale={1.23}>
        <group position={[-1.127, 1.776, -0.811]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[0.785, 0.571, 0.454]}>
          <mesh geometry={nodes['Shack_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
          <mesh geometry={nodes['Shack_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
        </group>
      </group>
      <mesh geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} />
      <mesh geometry={nodes['Island_01_-_Default_0'].geometry} material={materials['01_-_Default']} rotation={[-Math.PI / 2, 0, 0]} scale={0.981} />
      <mesh geometry={nodes['CoCoNut001_05_-_Default_0'].geometry} material={materials['05_-_Default']} position={[4.473, 53.076, -36.43]} rotation={[-Math.PI / 2, 0, 0]} scale={0.383} />
      <mesh geometry={nodes['CoCoNut002_05_-_Default_0'].geometry} material={materials['05_-_Default']} position={[8.213, 53.326, -38.515]} rotation={[-Math.PI / 2, 0, 0]} scale={0.383} />
      <mesh geometry={nodes['CoCoNut003_05_-_Default_0'].geometry} material={materials['05_-_Default']} position={[37.157, 50.676, -0.465]} rotation={[-Math.PI / 2, 0, 0]} scale={0.383} />
    </group>
    </mesh>
  )
}

useGLTF.preload('./models/island/island_2.glb')

export default Island_2