/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/island/island_4.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Island_4 = ({ scale, position, onClick, props }) => {
  const { nodes, materials } = useGLTF('./models/island/island_4.glb')
  const meshRef = useRef();
  
  const handleOnClick = () => {
    onClick(); // 부모 컴포넌트로 클릭 이벤트 전달
  };
  
  return (
    <mesh
      ref={meshRef}
      scale={scale}
      position={position}
      onClick={handleOnClick}
    >
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1776.018, 905.927, -1719.374]} rotation={[-1.634, -0.001, 0.626]} scale={[54.934, 54.934, 1059.561]}>
            <mesh geometry={nodes.Cube_coconut_base_0.geometry} material={materials.coconut_base} />
            <mesh geometry={nodes.Cube_palm_base_0.geometry} material={materials.palm_base} />
          </group>
          <group position={[-1625.321, 957.642, -3674.148]} rotation={[-1.634, -0.001, -0.914]} scale={[65.042, 65.042, 1059.561]}>
            <mesh geometry={nodes.Cube002_coconut_base_0.geometry} material={materials.coconut_base} />
            <mesh geometry={nodes.Cube002_palm_base_0.geometry} material={materials.palm_base} />
          </group>
          <group position={[-1085.325, 498.493, -5103.264]} rotation={[-1.634, -0.001, -0.914]} scale={[65.042, 65.042, 1059.561]}>
            <mesh geometry={nodes.Cube018_coconut_base_0.geometry} material={materials.coconut_base} />
            <mesh geometry={nodes.Cube018_palm_base_0.geometry} material={materials.palm_base} />
          </group>
          <group position={[-2944.708, 1815.338, -4462.792]} rotation={[-2.929, 0.077, -2.34]} scale={[65.042, 65.042, 1059.561]}>
            <mesh geometry={nodes.Cube019_coconut_base_0.geometry} material={materials.coconut_base} />
            <mesh geometry={nodes.Cube019_palm_base_0.geometry} material={materials.palm_base} />
          </group>
          <group position={[-277.918, 2838.113, -2773.363]} rotation={[1.298, -0.046, -2.827]} scale={[42.382, 60.737, 60.737]}>
            <mesh geometry={nodes.palm_coconut_base_0.geometry} material={materials.coconut_base} />
            <mesh geometry={nodes.palm_leaf_0.geometry} material={materials.leaf} />
            <mesh geometry={nodes.palm_palm_base_0.geometry} material={materials.palm_base} />
          </group>
          <group position={[1139.527, -252.267, -5648.225]} rotation={[1.452, 0.087, 1.842]} scale={[190.127, 190.127, 124.512]}>
            <mesh geometry={nodes.savior_circle_red_savior_0.geometry} material={materials.red_savior} />
            <mesh geometry={nodes.savior_circle_white_savior_0.geometry} material={materials.white_savior} />
          </group>
          <mesh geometry={nodes.anchor_metal_0.geometry} material={materials.metal} position={[2406.183, -171.175, -7528.28]} rotation={[0.632, -0.085, -0.329]} scale={73.176} />
          <mesh geometry={nodes.cococnut_coconut_0.geometry} material={materials.coconut} position={[-279.195, 2800.896, -2650.854]} rotation={[-1.634, -0.001, -1.797]} scale={65.374} />
          <mesh geometry={nodes.Cube012_rocks_0.geometry} material={materials.rocks} position={[-1352.394, -143.157, -7770.19]} rotation={[-1.653, -0.279, 2.304]} scale={229.135} />
          <mesh geometry={nodes.Cube015_rocks_0.geometry} material={materials.rocks} position={[-507.767, 4.749, -7754.915]} rotation={[-0.957, -0.488, -2.22]} scale={260.858} />
          <mesh geometry={nodes.Cube016_rocks_0.geometry} material={materials.rocks} position={[116.852, -275.017, -8017.935]} rotation={[-1.653, -0.279, 2.304]} scale={229.135} />
          <mesh geometry={nodes.Cube022_rocks_0.geometry} material={materials.rocks} position={[418.948, 630.95, -4469.228]} rotation={[-1.79, 0.209, -2.368]} scale={292.203} />
          <mesh geometry={nodes.Cube023_rock2_0.geometry} material={materials.rock2} position={[-362.478, 1213.185, -3795.805]} rotation={[-1.685, 0.286, -2.439]} scale={292.203} />
          <mesh geometry={nodes.Cube024_rocks_0.geometry} material={materials.rocks} position={[3518.565, 410.957, -3891.223]} rotation={[-1.79, 0.209, -2.368]} scale={[232.799, 168.07, 326.474]} />
          <mesh geometry={nodes.Cube025_rocks_0.geometry} material={materials.rocks} position={[776.22, 224.071, -6047.028]} rotation={[-2.536, 0.641, 2.78]} scale={[500.345, 183.299, 335.655]} />
          <mesh geometry={nodes.Cube030_rock2_0.geometry} material={materials.rock2} position={[-2195.742, -104.742, -8450.914]} rotation={[-0.07, -0.306, -0.19]} scale={[362.833, 250.672, 359.649]} />
          <mesh geometry={nodes.grass_grass_0.geometry} material={materials.grass} position={[-682.699, 281.65, -3292.567]} rotation={[-1.261, 0.039, -1.103]} scale={[570.527, 569.251, 367.508]} />
          <mesh geometry={nodes.Icosphere001_coconut_0.geometry} material={materials.coconut} position={[-1724.986, 2702.099, -3904.915]} rotation={[-1.634, -0.001, -0.914]} scale={65.374} />
          <mesh geometry={nodes.Icosphere002_coconut_0.geometry} material={materials.coconut} position={[-1184.989, 2242.948, -5334.033]} rotation={[-1.634, -0.001, -0.914]} scale={65.374} />
          <mesh geometry={nodes.Icosphere003_coconut_0.geometry} material={materials.coconut} position={[-233.611, 2770.426, -2844.839]} rotation={[-1.634, -0.001, -1.797]} scale={65.374} />
          <mesh geometry={nodes.Icosphere005_coconut_0.geometry} material={materials.coconut} position={[-1137.138, 2271.639, -5160.432]} rotation={[-1.634, -0.001, -0.914]} scale={65.374} />
          <mesh geometry={nodes.Icosphere006_coconut_0.geometry} material={materials.coconut} position={[-1022.768, 2266.26, -5223.869]} rotation={[-1.634, -0.001, -0.914]} scale={65.374} />
          <mesh geometry={nodes.Icosphere007_coconut_0.geometry} material={materials.coconut} position={[-195.731, 2827.458, -2733.418]} rotation={[-1.634, -0.001, -1.797]} scale={65.374} />
          <mesh geometry={nodes.island_island_0.geometry} material={materials.island} position={[-1037.257, -656.569, -3409.192]} rotation={[-1.634, -0.001, -0.441]} scale={[1157.128, 1157.128, 770.941]} />
          <mesh geometry={nodes.ladder1_boat_dark_0.geometry} material={materials.boat_dark} position={[-234.412, 29.759, -7074.466]} rotation={[-0.327, 1.239, 0.001]} scale={[329.903, 87.394, 202.181]} />
          <mesh geometry={nodes.mast1_island_0.geometry} material={materials.island} position={[-1856.32, 762.703, -5366.961]} rotation={[0.373, -1.413, -0.785]} scale={[-55.735, -55.735, -751.602]} />
          <mesh geometry={nodes.Plane002_leaf_0.geometry} material={materials.leaf} position={[-1708.82, 2707.742, -2058.425]} rotation={[1.508, 0.001, 0.316]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane003_leaf_0.geometry} material={materials.leaf} position={[-1637.555, 3019.731, -1984.978]} rotation={[2.045, 0.433, -2.584]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane004_leaf_0.geometry} material={materials.leaf} position={[-2155.833, 2835.895, -1854.992]} rotation={[1.517, -0.084, 1.848]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane005_leaf_0.geometry} material={materials.leaf} position={[-1650.821, 3010.935, -1555.972]} rotation={[0.898, 0.311, -0.467]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane006_leaf_0.geometry} material={materials.leaf} position={[-2079.055, 2697.273, -2012.946]} rotation={[1.389, 0.213, 2.379]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane007_leaf_0.geometry} material={materials.leaf} position={[-1613.036, 2740.198, -1561.102]} rotation={[1.361, 0.017, 2.298]} scale={[47.31, 117.387, 327.305]} />
          <mesh geometry={nodes.Plane008_leaf_0.geometry} material={materials.leaf} position={[-1477.728, 2709.919, -1780.524]} rotation={[1.525, -0.233, 1.591]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.Plane009_leaf_0.geometry} material={materials.leaf} position={[-2013.344, 2765.823, -1498.67]} rotation={[1.629, 0.288, 0.64]} scale={[48.516, 69.527, 69.527]} />
          <mesh geometry={nodes.Plane010_leaf_0.geometry} material={materials.leaf} position={[-2067.401, 3007.868, -1742.232]} rotation={[1.479, -0.674, 1.47]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane011_leaf_0.geometry} material={materials.leaf} position={[-1543.146, 2805.56, -1962.836]} rotation={[1.57, -0.016, 0.906]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.Plane012_leaf_0.geometry} material={materials.leaf} position={[-1776.46, 2736.783, -1469.531]} rotation={[1.66, -0.107, -0.15]} scale={[52.824, 99.952, 160.057]} />
          <mesh geometry={nodes.Plane013_leaf_0.geometry} material={materials.leaf} position={[-2070.127, 2715.087, -1637.246]} rotation={[1.636, 0.173, 1.026]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.Plane025_leaf_0.geometry} material={materials.leaf} position={[-1400.208, 2777.671, -3727.322]} rotation={[1.508, 0.001, 1.856]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane026_leaf_0.geometry} material={materials.leaf} position={[-1491.203, 3088.344, -3672.441]} rotation={[1.03, 0.498, -0.799]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane027_leaf_0.geometry} material={materials.leaf} position={[-1625.165, 2864.915, -4173.876]} rotation={[1.593, 0.008, -2.896]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane028_leaf_0.geometry} material={materials.leaf} position={[-1918.973, 3052.201, -3670.202]} rotation={[1.116, -0.564, 0.859]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane029_leaf_0.geometry} material={materials.leaf} position={[-1456.372, 2741.385, -4094.448]} rotation={[1.29, -0.109, -2.389]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane030_leaf_0.geometry} material={materials.leaf} position={[-1895.383, 2785.178, -3616.398]} rotation={[1.487, -0.145, -2.449]} scale={[47.31, 117.387, 327.305]} />
          <mesh geometry={nodes.Plane031_leaf_0.geometry} material={materials.leaf} position={[-1670.387, 2777.02, -3487.24]} rotation={[1.742, 0.01, 3.128]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.Plane032_leaf_0.geometry} material={materials.leaf} position={[-1971.695, 2781.928, -4015.105]} rotation={[1.223, 0.126, 2.216]} scale={[48.516, 69.527, 69.527]} />
          <mesh geometry={nodes.Plane033_leaf_0.geometry} material={materials.leaf} position={[-1745.894, 3034.749, -4092.078]} rotation={[2.182, -0.041, 3.034]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane034_leaf_0.geometry} material={materials.leaf} position={[-1496.676, 2879.504, -3564.605]} rotation={[1.527, 0.062, 2.445]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.Plane035_leaf_0.geometry} material={materials.leaf} position={[-1991.567, 2765.939, -3776.033]} rotation={[1.622, 0.149, 1.373]} scale={[52.824, 99.952, 160.057]} />
          <mesh geometry={nodes.Plane036_leaf_0.geometry} material={materials.leaf} position={[-1831.985, 2736.432, -4073.524]} rotation={[1.338, 0.132, 2.589]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.Plane037_leaf_0.geometry} material={materials.leaf} position={[-860.213, 2318.522, -5156.438]} rotation={[1.508, 0.001, 1.856]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane038_leaf_0.geometry} material={materials.leaf} position={[-951.207, 2629.194, -5101.56]} rotation={[1.03, 0.498, -0.799]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane039_leaf_0.geometry} material={materials.leaf} position={[-1085.17, 2405.765, -5602.994]} rotation={[1.593, 0.008, -2.896]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane040_leaf_0.geometry} material={materials.leaf} position={[-1378.978, 2593.052, -5099.318]} rotation={[1.116, -0.564, 0.859]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane041_leaf_0.geometry} material={materials.leaf} position={[-916.376, 2282.235, -5523.564]} rotation={[1.29, -0.109, -2.389]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane042_leaf_0.geometry} material={materials.leaf} position={[-1355.387, 2326.028, -5045.516]} rotation={[1.487, -0.145, -2.449]} scale={[47.31, 117.387, 327.305]} />
          <mesh geometry={nodes.Plane043_leaf_0.geometry} material={materials.leaf} position={[-1130.392, 2317.869, -4916.357]} rotation={[1.742, 0.01, 3.128]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.Plane044_leaf_0.geometry} material={materials.leaf} position={[-1431.699, 2322.779, -5444.223]} rotation={[1.223, 0.126, 2.216]} scale={[48.516, 69.527, 69.527]} />
          <mesh geometry={nodes.Plane045_leaf_0.geometry} material={materials.leaf} position={[-1205.898, 2575.6, -5521.195]} rotation={[2.182, -0.041, 3.034]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane046_leaf_0.geometry} material={materials.leaf} position={[-956.68, 2420.354, -4993.722]} rotation={[1.527, 0.062, 2.445]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.Plane047_leaf_0.geometry} material={materials.leaf} position={[-1451.571, 2306.79, -5205.148]} rotation={[1.622, 0.149, 1.373]} scale={[52.824, 99.952, 160.057]} />
          <mesh geometry={nodes.Plane048_leaf_0.geometry} material={materials.leaf} position={[-1291.99, 2277.281, -5502.643]} rotation={[1.338, 0.132, 2.589]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.Plane049_leaf_0.geometry} material={materials.leaf} position={[-3076.649, 2456.438, -4222.448]} rotation={[1.574, 0.168, 3.071]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane050_leaf_0.geometry} material={materials.leaf} position={[-3227.844, 2742.053, -4280.526]} rotation={[0.943, -0.079, 0.321]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane051_leaf_0.geometry} material={materials.leaf} position={[-2766.49, 2627.456, -4586.015]} rotation={[1.599, 0.25, -1.686]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane052_leaf_0.geometry} material={materials.leaf} position={[-3368.831, 2683.238, -4681.727]} rotation={[2.004, -0.359, 2.232]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane053_leaf_0.geometry} material={materials.leaf} position={[-2753.088, 2498.79, -4403.463]} rotation={[1.602, -0.073, -1.164]} scale={[58.152, 132.651, 132.651]} />
          <mesh geometry={nodes.Plane054_leaf_0.geometry} material={materials.leaf} position={[-3349.716, 2412.594, -4647.97]} rotation={[1.705, 0.096, -1.25]} scale={[47.31, 117.387, 327.305]} />
          <mesh geometry={nodes.Plane055_leaf_0.geometry} material={materials.leaf} position={[-3388.278, 2388.406, -4392.433]} rotation={[1.652, 0.391, -1.961]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.Plane056_leaf_0.geometry} material={materials.leaf} position={[-3011.722, 2492.981, -4857.965]} rotation={[1.358, -0.056, -2.859]} scale={[48.516, 69.527, 69.527]} />
          <mesh geometry={nodes.Plane057_leaf_0.geometry} material={materials.leaf} position={[-2920.772, 2768.365, -4666.337]} rotation={[1.938, 0.765, -2.221]} scale={[46.294, 105.601, 105.601]} />
          <mesh geometry={nodes.Plane058_leaf_0.geometry} material={materials.leaf} position={[-3281.07, 2514.629, -4253.732]} rotation={[1.522, 0.207, -2.613]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.Plane059_leaf_0.geometry} material={materials.leaf} position={[-3232.921, 2423.761, -4794.046]} rotation={[1.469, 0.325, 2.622]} scale={[52.824, 99.952, 160.057]} />
          <mesh geometry={nodes.Plane060_leaf_0.geometry} material={materials.leaf} position={[-2900.191, 2469.064, -4748.463]} rotation={[1.392, 0.053, -2.471]} scale={[42.382, 60.737, 60.737]} />
          <mesh geometry={nodes.rock1_rock2_0.geometry} material={materials.rock2} position={[-870.29, 944.273, -557.503]} rotation={[-1.302, 0.084, -2.389]} scale={292.203} />
          <mesh geometry={nodes.rock4_rock2_0.geometry} material={materials.rock2} position={[1534.62, 13.595, -7243.988]} rotation={[2.036, 0.801, 1.344]} scale={[362.833, 250.672, 359.649]} />
          <mesh geometry={nodes.rock5_rocks_0.geometry} material={materials.rocks} position={[-2662.023, -180.565, -7856.883]} rotation={[-1.653, -0.279, 2.304]} scale={281.851} />
          <mesh geometry={nodes.rock7_rock2_0.geometry} material={materials.rock2} position={[2906.711, -143.931, -6957.376]} rotation={[-1.698, 0.114, -2.506]} scale={[489.649, 449.842, 497.556]} />
        </group>
      </group>
    </group>
    </mesh>
  )
}

useGLTF.preload('./models/island/island_4.glb')

export default Island_4
