/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/island/island_3.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Island_3 = ({ scale, position, onClick, props }) => {
  const { nodes, materials } = useGLTF('./models/island/island_3.glb')
  const meshRef = useRef();
  
  const handleOnClick = () => {
    onClick(); // 부모 컴포넌트로 클릭 이벤트 전달
  };
  
  return (
    <mesh
      ref={meshRef}
      scale={scale}
      position={position}
      onClick={handleOnClick}
    >
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.008}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 92.712]}>
            <mesh geometry={nodes.Icosphere_2_TTLE1_SAND_0.geometry} material={materials['2_TTLE1_SAND']} />
            <mesh geometry={nodes.Icosphere_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} />
            <mesh geometry={nodes.Icosphere_2_TTLE3_SKIN_0.geometry} material={materials['2_TTLE3_SKIN']} />
          </group>
          <group position={[-51.791, 3661.121, 35.099]} rotation={[-Math.PI / 2, 0, 0]} scale={[118.208, 118.208, 109.593]}>
            <mesh geometry={nodes.Icosphere013_2_TTLE1_SAND_0.geometry} material={materials['2_TTLE1_SAND']} />
            <mesh geometry={nodes.Icosphere013_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} />
          </group>
          <group position={[-61.387, 3213.207, -1029.621]} rotation={[-1.762, 0.075, -1.772]} scale={[80.352, 80.352, 74.496]}>
            <mesh geometry={nodes.Icosphere028_2_TTLE1_SAND_0.geometry} material={materials['2_TTLE1_SAND']} />
            <mesh geometry={nodes.Icosphere028_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} />
          </group>
          <group position={[1434.042, 3710.918, -306.677]} rotation={[-1.55, 0.005, 1.333]} scale={[132.006, 132.006, 122.385]}>
            <mesh geometry={nodes.Icosphere029_2_TTLE1_SAND_0.geometry} material={materials['2_TTLE1_SAND']} />
            <mesh geometry={nodes.Icosphere029_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} />
          </group>
          <mesh geometry={nodes.Cube005_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} position={[1432.996, 1997.087, -541.625]} rotation={[-Math.PI / 2, 0, 0]} scale={71.685} />
          <mesh geometry={nodes.Cube006_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} position={[1697.364, 2085.329, -350.429]} rotation={[-1.534, 0.25, 0.013]} scale={71.685} />
          <mesh geometry={nodes.Cube007_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} position={[1755.122, 2024.649, -90.225]} rotation={[-1.49, 0.624, -0.05]} scale={71.685} />
          <mesh geometry={nodes.Cube008_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} position={[1205.252, 2227.458, -217.49]} rotation={[-1.25, -0.236, -2.134]} scale={71.685} />
          <mesh geometry={nodes.Cube009_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} position={[-194.254, 2318.427, 300.155]} rotation={[-1.25, -0.236, -2.134]} scale={71.685} />
          <mesh geometry={nodes.Cube010_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} position={[-257.092, 2420.358, -621.834]} rotation={[-1.292, -0.147, -2.101]} scale={71.685} />
          <mesh geometry={nodes.Cube011_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} position={[58.463, 2286.861, -74.343]} rotation={[-1.883, -0.038, 1.634]} scale={60.378} />
          <mesh geometry={nodes.Cube012_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} position={[400.93, 2177.635, -465.766]} rotation={[-1.883, -0.038, 1.634]} scale={29.268} />
          <mesh geometry={nodes.Cube013_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} position={[-451.773, 2013.788, 646.551]} rotation={[-1.538, -0.315, 1.681]} scale={29.268} />
          <mesh geometry={nodes.Cube014_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} position={[335.992, 2069.406, 1202.259]} rotation={[-1.425, -0.151, 1.666]} scale={29.268} />
          <mesh geometry={nodes.Cube015_2_TTLE2_GRASS_0.geometry} material={materials['2_TTLE2_GRASS']} position={[-107.768, 2137.699, -1051.898]} rotation={[-2.412, -0.251, 1.432]} scale={29.268} />
          <mesh geometry={nodes.Sphere_Material002_0.geometry} material={materials['Material.002']} position={[1428.493, 5422.343, -584.954]} rotation={[-Math.PI / 2, 0, 0]} scale={151.745} />
          <mesh geometry={nodes.Sphere001_Material002_0.geometry} material={materials['Material.002']} position={[1596.533, 5523.125, -424.865]} rotation={[-1.684, -0.452, -0.12]} scale={151.745} />
          <mesh geometry={nodes.Sphere002_Material002_0.geometry} material={materials['Material.002']} position={[-48.112, 5276.662, -91.286]} rotation={[-1.684, -0.452, -0.12]} scale={151.745} />
          <mesh geometry={nodes.Sphere003_Material002_0.geometry} material={materials['Material.002']} position={[-128.851, 5204.175, 235.777]} rotation={[-1.742, 0.107, -0.087]} scale={151.745} />
          <mesh geometry={nodes.Sphere004_Material002_0.geometry} material={materials['Material.002']} position={[66.055, 5320.374, 80.321]} rotation={[-1.742, 0.107, -0.087]} scale={151.745} />
          <mesh geometry={nodes.Sphere005_Material002_0.geometry} material={materials['Material.002']} position={[1506.906, 5521.973, -84.331]} rotation={[-1.742, 0.107, -0.087]} scale={159.399} />
          <mesh geometry={nodes.Sphere006_Material002_0.geometry} material={materials['Material.002']} position={[1143.381, 1986.179, 211.91]} rotation={[-1.742, 0.107, -0.087]} scale={159.399} />
          <mesh geometry={nodes.Sphere007_Material002_0.geometry} material={materials['Material.002']} position={[487.96, 2168.661, -609.201]} rotation={[-1.742, 0.107, -0.087]} scale={159.399} />
          <mesh geometry={nodes.Sphere008_Material002_0.geometry} material={materials['Material.002']} position={[-128.446, 2234.346, -202.267]} rotation={[-1.742, 0.107, -0.087]} scale={159.399} />
          <mesh geometry={nodes.Sphere009_Material002_0.geometry} material={materials['Material.002']} position={[-40.719, 2221.134, -890.429]} rotation={[-1.742, 0.107, -0.087]} scale={159.399} />
          <mesh geometry={nodes.Sphere010_Material002_0.geometry} material={materials['Material.002']} position={[1448.713, 2014.193, -990.838]} rotation={[-1.742, 0.107, -0.087]} scale={159.399} />
        </group>
      </group>
    </group>
    </mesh>
  )
}

useGLTF.preload('./models/island/island_3.glb')

export default Island_3
