/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/ship/ship1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Ship1 = (props) => {
  const { nodes, materials } = useGLTF('./models/ship/ship1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.453, -1.048]}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials.Fabric} />
      </group>
      <group position={[0, 2.05, 1.134]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.Fabric} />
      </group>
      <group position={[0, 2.486, 0.051]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.Fabric} />
      </group>
      <group position={[-0.002, -0.071, -0.048]}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Fabric} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials.LightWood} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials.DarkRed} />
      </group>
      <mesh geometry={nodes.Rudder.geometry} material={materials.Wood} position={[0, 1.273, -1.908]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.087, 0.013, 0.087]} />
    </group>
  )
}

useGLTF.preload('./models/ship/ship1.glb')

export default Ship1;
