import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import styles from "./globals.module.scss";
import getCurrentUser from "./actions/getCurrentUser";
import ToastProvider from "@/components/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body>
          <Navbar currentUser={currentUser}/>
          <ToastProvider />
            {children}
      </body>
    </html>
  );
}
